google:
  client:
    clientId: 126792298774-cj50rc1p9tjt3msebckhmhjk9uasgaud.apps.googleusercontent.com
    clientSecret: 91M7AX4xoCwAOoaHih7AaNQh
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope:
      - email
      - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
github:
  client:
    clientId: 30d6c89c44f9ed8f2dd1
    clientSecret: 6927436aec736e0d29518865d4ce164d5f416502
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    scope:
      - user:email
  resource:
    userInfoUri: https://api.github.com/user
gitlab:
  client:
    clientId: 6261e0e9ae982441ab3e9b02f0fefc1b6286081712cf587f76b7ca9981032075
    clientSecret: dee47f35ac2ce3d61f83b6e59a92387868daaf1f48038d0f41aba2b1a9faeb14
    accessTokenUri: https://gitlab.com/oauth/token
    userAuthorizationUri: https://gitlab.com/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://gitlab.com/api/v4/user
spring:
    mail:
       host: smtp.gmail.com
       port: 587
       username: movierental.terlecki
       password: plotka123
       properties.mail.smtp:
                 auth: true
                 starttls.enable: true
       protocol: smtp
       default-encoding: UTF-8